CREATE TABLE IF NOT EXISTS MPA (
	ID INTEGER NOT NULL,
	NAME CHARACTER VARYING NOT NULL,
	CONSTRAINT MPA_PK PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS FILMS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(255) NOT NULL,
	DESCRIPTION CHARACTER VARYING(200),
	RELEASE_DATE DATE NOT NULL,
	ID_MPA INTEGER NOT NULL,
	DURATION INTEGER NOT NULL,
	CONSTRAINT FILMS_PK PRIMARY KEY (ID),
	CONSTRAINT FILMS_FK FOREIGN KEY (ID_MPA) REFERENCES MPA(ID)
	);

CREATE TABLE IF NOT EXISTS USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING,
	EMAIL CHARACTER VARYING NOT NULL,
	LOGIN CHARACTER VARYING NOT NULL,
	BIRTHDAY DATE NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS FRIENDSHIP (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	CONSTRAINT FRIENDSHIP_PK PRIMARY KEY (USER_ID, FRIEND_ID),
	CONSTRAINT FRIENDSHIP_FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
	CONSTRAINT FRIENDSHIP_FK_FRIEND FOREIGN KEY (FRIEND_ID) REFERENCES USERS(ID)
);
CREATE TABLE IF NOT EXISTS FILMS_USERS (
	ID_FILM INTEGER NOT NULL,
	ID_USER INTEGER NOT NULL,
	CONSTRAINT FILMS_USERS_PK PRIMARY KEY (ID_FILM, ID_USER),
	CONSTRAINT FILMS_USERS_FK_FILMS FOREIGN KEY (ID_FILM) REFERENCES FILMS(ID),
	CONSTRAINT FILMS_USERS_FK_USERS FOREIGN KEY (ID_USER) REFERENCES USERS(ID)
);
CREATE TABLE IF NOT EXISTS GENRES (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING NOT NULL,
	CONSTRAINT GENRES_PK PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS GENRES_FILMS (
	GENRE_ID INTEGER NOT NULL,
	FILM_ID INTEGER NOT NULL,
	CONSTRAINT GENRES_FILMS_PK PRIMARY KEY (GENRE_ID, FILM_ID),
	CONSTRAINT GENRES_FILMS_FK_FILMS FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID),
	CONSTRAINT GENRES_FILMS_FK_GENRES FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);



